backend:
  name: github
  repo: n3xtcoder/send
  branch: review-11-sept-2019
  base_url: https://send-auth.herokuapp.com

publish_mode: editorial_workflow

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: "sponsors"
    label: "Förderer"
    folder: "src/sponsors"
    create: true
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Bild", name: "image", widget: "image"}
      - {label: "Homepage", name: "homepage", widget: "string", required: false}
      - {label: "Email", name: "mail", widget: "string", required: false}
      - {label: "Organisation", name: "organization", widget: "boolean"}
  - name: "partner"
    label: "Partner"
    folder: "src/partners"
    create: true
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Logo", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "string"}
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "article"}
      - {label: "Image Mask", name: "clip", widget: "hidden", default: "clip_article"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "markdown", pattern: ['^.{0,350}$', "Must have between 0 and 350 characters"] }
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Category", name: "category", widget: "select", options:["news","event"]}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "members"
    label: "Mitglieder"
    folder: "src/members"
    slug: "{{slug}}_{{year}}-{{month}}-{{day}}"
    create: true
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Impact Area", name: "impactArea", widget: "select", multiple: true, options: [
          "Armut",
          "Bildung",
          "Demographischer Wandel",
          "Demokratie & Engagement von Bürger*innen",
          "Dienstleistungen für Sozialunternehmen",
          "Entrepreneurshipförderung",
          "Flucht und Migration",
          "Gesundheit",
          "Inklusion von Menschen mit Behinderung",
          "Integration","Internationale Zusammenarbeit",
          "Menschenrechte",
          "Stadtentwicklung",
          "Umwelt– & Klimaschutz",
          "Zukunft der Arbeit",
          "Sonstige"
        ]}
      - {label: "Organization", name: "organization", widget: "boolean"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Email", name: "email", widget: "string", required: false}
      - {label: "Link", name: "link", widget: "string", required: false}
      - {label: "City", name: "city", widget: "string"}
      - {label: "Postal Code", name: "postalCode", widget: "number"}
      - {label: "Federal State", name: "federalState", widget: "select", options: [
          "Baden-Württemberg",
          "Bayern","Berlin",
          "Brandenburg",
          "Bremen",
          "Hamburg",
          "Hessen",
          "Mecklenburg-Vorpommern",
          "Niedersachsen",
          "Nordrhein-Westfalen",
          "Rheinland-Pfalz",
          "Saarland",
          "Sachsen",
          "Sachsen-Anhalt",
          "Schleswig-Holstein",
          "Thüringen"
      ]}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "index"
        fields:
          - {label: "Meta-Pagetitle for google ", name: "title", widget: "string"}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "Tagline-Large", name: "tagline_large", widget: "markdown"}
          - {label: "Paragraph", name: "paragraph", widget: "text"}
          - {label: "Section 1", name: "section_1", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Paragraph", name: "paragraph", widget: "markdown"},
              {label: "Boxes", name: "boxes", widget: "list", fields: [
                {label: "Box", name: "description", widget: "markdown"}
              ]}
            ]}
          - {label: Section 2, name: section_2, widget: object, fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Subtitle", name: "subtitle", widget: "string"},
              {label: "Paragraph", name: "paragraph", widget: "markdown"},
              {label: "Button", name: "cta", widget: "object", fields: [
                {label: "Label", name: "label", widget: "string"},
                {label: "Link", name: "link", widget: "string"}
              ]},
              {label: "Profile Boxes", name: "profile_boxes", widget: "list", fields: [
                  {label: "Profile Image", name: "image", widget: "image"},
                  {label: "Name", name: "name", widget: "string"},
                  {label: "Email", name: "email", widget: "string"},
                  {label: "Project", name: "project", widget: "string"},
                  {label: "Description", name: "description", widget: "string"}
              ]}
            ]}
          - {label: "Sticky CTA", name: "cta_sticky", widget: "object", fields: [
              {label: "Text", name: "text", widget: "string", pattern: ['^.{0,51}$', "Must not be longer than 51 characters!"]},
              {label: "Link", name: "link", widget: "string"},
              {label: "HexColor", name: "hexColor", widget: "string"},
              {lable: "Show on page", name: "showOnPage", widget: "boolean"}
            ]}
      - file: "src/pages/netzwerk.md"
        label: "Netzwerk"
        name: "netzwerk"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden"}
          - {label: "Image Mask", name: "clip", widget: "hidden"}
          - {label: "Meta-Pagetitle for google ", name: "title", widget: "string"}
          - {label: "Section 1", name: "section_1", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Paragraph", name: "paragraph", widget: "markdown"},
            ]}
          - {label: "Section 2", name: "section_2", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Paragraph", name: "paragraph", widget: "markdown"},
              {label: "Button", name: "cta", widget: "object", fields: [
                {label: "Label", name: "label", widget: "string"},
                {label: "Link", name: "link", widget: "string"}
              ]}
            ]}
          - {label: "Sticky CTA", name: "cta_sticky", widget: "object", fields: [
                {label: "Text", name: "text", widget: "string", pattern: ['^.{0,51}$', "Must not be longer than 51 characters!"]},
                {label: "Link", name: "link", widget: "string"},
                {label: "HexColor", name: "hexColor", widget: "string"},
                {lable: "Show on page", name: "showOnPage", widget: "boolean"}
              ]}
      - file: "src/pages/ueber-uns.md"
        label: "Über uns"
        name: "ueber-uns"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden"}
          - {label: "Image Mask", name: "clip", widget: "hidden"}
          - {label: "Meta-Pagetitle for google ", name: "title", widget: "string"}
          - {label: "Section 1", name: "section_1", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Paragraph", name: "paragraph", widget: "markdown"},
            ]}
          - {label: "Section 2", name: "section_2", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Image", name: "image", widget: image},
              {label: "Paragraph", name: "paragraph", widget: "markdown"}
            ]}
          - {label: "Section 3", name: "section_3", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Profile Boxes", name: "profile_boxes", widget: "list", fields: [
                {label: "Name", name: "name", widget: "string"},
                {label: "Rolle", name: "role", widget: "string"},
                {label: "Organisation", name: "organization", widget: "string"},
                {label: "Image", name: "image", widget: "image"}
              ]}
            ]}
          - {label: "Section 4", name: "section_4", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Paragraph", name: "paragraph", widget: "markdown"}
            ]}
          - {label: "Sticky CTA", name: "cta_sticky", widget: "object", fields: [
              {label: "Text", name: "text", widget: "string", pattern: ['^.{0,51}$', "Must not be longer than 51 characters!"]},
              {label: "Link", name: "link", widget: "string"},
              {label: "HexColor", name: "hexColor", widget: "string"},
              {lable: "Show on page", name: "showOnPage", widget: "boolean"}
            ]}
      - file: "src/pages/positionen.md"
        label: "Positionen"
        name: "positionen"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden"}
          - {label: "Image Mask", name: "clip", widget: "hidden"}
          - {label: "Meta-Pagetitle for google ", name: "title", widget: "string"}
          - {label: "Section 1", name: "section_1", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Paragraph", name: "paragraph", widget: "markdown"}
            ]}
          - {label: "Section 2", name: "section_2", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Button", name: "cta", widget: "object", fields: [
                {label: "Label", name: "label", widget: "string"},
                {label: "File", name: "link", widget: "file"}
              ]},
              {label: "Boxes", name: "boxes", widget: "list", fields: [
                {label: "Illustration", name: "icon", widget: "hidden"},
                {label: "Description", name: "description", widget: "markdown"}
              ]}
            ]}
          - {label: "Sticky CTA", name: "cta_sticky", widget: "object", fields: [
              {label: "Text", name: "text", widget: "string", pattern: ['^.{0,51}$', "Must not be longer than 51 characters!"]},
              {label: "Link", name: "link", widget: "string"},
              {label: "HexColor", name: "hexColor", widget: "string"},
              {lable: "Show on page", name: "showOnPage", widget: "boolean"}
            ]}
      - file: "src/pages/mitgliedschaft.md"
        label: Mitgliedschaft
        name: "membership"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden"}
          - {label: "Image Mask", name: "clip", widget: "hidden", default: "clip_positionen"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Top Image", name: "image", widget: "image"}
          - {label: "Button Link", name: "cta_link", widget: "object", fields: [
              {label: "Label", name: "label", widget: "string"},
              {label: "Url", name: "link", widget: "string"}
            ]}
          - {label: "Button Download", name: "cta_download", widget: "object", fields: [
              {label: "Label", name: "label", widget: "string"},
              {label: "File", name: "link", widget: "string"}
            ]}
          - {label: "Mitgliedschaftsarten", name: "section_1", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Column 1", name: "column_1", widget: "object", fields: [
                {label: "Column Title", name: "title", widget: "markdown"},
                {label: "Column Text", name: "paragraph", widget: "markdown"}
              ]},
              {label: "Column 2", name: "column_2", widget: "object", fields: [
                {label: "Column Title", name: "title", widget: "markdown"},
                {label: "Column Text", name: "paragraph", widget: "markdown"}
              ]}
            ]}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Sticky CTA", name: "cta_sticky", widget: "object", fields: [
              {label: "Text", name: "text", widget: "string", pattern: ['^.{0,51}$', "Must not be longer than 51 characters!"]},
              {label: "Link", name: "link", widget: "string"},
              {label: "HexColor", name: "hexColor", widget: "string"},
              {lable: "Show on page", name: "showOnPage", widget: "boolean"}
            ]}
      - file: "src/pages/blog.md"
        label: "Blog"
        name: "blog"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden"}
          - {label: "Meta-Pagetitle for google", name: "title", widget: "string"}
          - {label: "Section 1", name: "section_1", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
            ]}
          - {label: "Sticky CTA", name: "cta_sticky", widget: "object", fields: [
              {label: "Text", name: "text", widget: "string", pattern: ['^.{0,51}$', "Must not be longer than 51 characters!"]},
              {label: "Link", name: "link", widget: "string"},
              {label: "HexColor", name: "hexColor", widget: "string"},
              {lable: "Show on page", name: "showOnPage", widget: "boolean"}
            ]}
      - file: "src/pages/partner.md"
        label: "Partner"
        name: "partner"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden"}
          - {label: "Image Mask", name: "clip", widget: "hidden"}
          - {label: "Page Title ", name: "title", widget: "string"}
          - {label: "Sticky CTA", name: "cta_sticky", widget: "object", fields: [
              {label: "Text", name: "text", widget: "string", pattern: ['^.{0,51}$', "Must not be longer than 51 characters!"]},
              {label: "Link", name: "link", widget: "string"},
              {label: "HexColor", name: "hexColor", widget: "string"},
              {lable: "Show on page", name: "showOnPage", widget: "boolean"}
            ]}
          - {label: "Section 1", name: "section_1", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Paragraph", name: "paragraph", widget: "markdown"}
            ]}
          - {label: "Section 2", name: "section_2", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Paragraph", name: "paragraph", widget: "markdown"}
            ]}
          - {label: "Section 3", name: "section_3", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Paragraph", name: "paragraph", widget: "markdown"}
            ]}
      - file: "src/pages/konferenz.md"
        label: "Konferenz 16.-17. März 2019"
        name: "konferenz"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "article"}
          - {label: "Image Mask", name: "clip", widget: "hidden", default: "clip_article"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/impressum.md"
        label: "Impressum"
        name: "impressum"
        fields:
          - {label: "Page Title ", name: "title", widget: "string"}
          - {label: "Template Key", name: "templateKey", widget: "hidden"}
          - {label: "Address", name: "address", widget: "markdown"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Bankverbindung", name: "bank", widget: "markdown"}
          - {label: "Section 1", name: "section_1", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Paragraph", name: "content", widget: "text"},
              {label: "Button", name: "cta", widget: "object", fields: [
                {label: "Label", name: "label", widget: "string"},
                {label: "File", name: "link", widget: "file"}
              ]},
            ]}
          - {label: "Section 2", name: "section_2", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Paragraph", name: "content", widget: "text"},
              {label: "Button", name: "cta", widget: "object", fields: [
                {label: "Label", name: "label", widget: "string"},
                {label: "File", name: "link", widget: "file"}
              ]}
            ]}
          - {label: "Section 3", name: "section_3", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Paragraph", name: "content", widget: "text"}
            ]}
          - {label: "Section 4", name: "section_4", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Paragraph", name: "content", widget: "text"}
            ]}
          - {label: "Section 5", name: "section_5", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
            ]}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/dsgvo.md"
        label: "DSGVO"
        name: "dsgvo"
        fields:
          - {label: "Page Title ", name: "title", widget: "string"}
          - {label: "Template Key", name: "templateKey", widget: "hidden"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/downloads.md"
        label: "Downloads"
        name: "downloads"
        fields:
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "Download Material", name: "downloadMaterial", widget: "list", fields: [
                {label: "Download Text", name: "downloadText", widget: "string"},
                {label: "Button Text", name: "buttonText", widget: "string"},
                {label: "File", name: "file", widget: "file"}
            ]}
