backend:
  name: github
  repo: n3xtcoder/send
  branch: cms

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "index"
        fields:
          - {label: "Path", name: "path", widget: "hidden", default: "/404"}
          - {label: "Image", name: "image", widget: "file"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "Tagline-Large", name: "tagline_large", widget: "text"}
          - {label: Section 1, name: section_1, widget: object, fields: [ {label: Boxes, name: boxes, widget: object, fields: [ {label: Box Text, name: description, widget: markdown}]}]}
  - name: "components"
    label: "Components"
    files:
      - file: "src/pages/components/member-cta-section.md"
        label: "Member CTA Section"
        name: "member-cta-section"
        fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: Content, name: content, widget: object, fields: [ {label: Blurbs, name: blurbs, widget: list, fields: [ {label: Text, name: text, widget: text}]}]}
            - {label: "Button Label", name: "button-label", widget: "string"}
